# Generated by Django 2.1.7 on 2019-03-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateTimeField(verbose_name='Birth Date')),
                ('salary', models.FloatField()),
                ('photo', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
